apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: prod
spec:
  encryptedData:
    TEST_ENV_SECRET: BASE64_ENCODED_STRING
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: prod
